### ISSUE TITLE
`Filewatcher` vs `FileWatcher` case change from rubygems

### ISSUE THREAD

**Issue by mbigras** [thomasfl/filewatcher#78] opened 2017-09-24 08:22 UTC
Hi thomas!

Thank you for such a great tool.
Wanted to let you know, I think something is happening with rubygems where the classname `Filewatcher` is getting changed to `FileWatcher`.

When I tried the API examples I kept getting the following error:

```
$ bundle exec ruby example.rb
example.rb:3:in `<main>': uninitialized constant Filewatcher (NameError)
```

I wasn't sure why but then I looked at the gem:

```
$ grep FileWatcher ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/filewatcher-0.5.4/lib/filewatcher.rb
class FileWatcher
```

See how the name got changed to camel case?

Thought you might want to know because it breaks the copy and pastable examples in your README.

**Comment by AlexWayfer** [comment] 2017-09-24 08:31
Hello!

Duplicate of #73.

**Closed** 2017-09-24 08:32 UTC
Labels: duplicate

**Comment by AlexWayfer** [comment] 2017-09-24 21:25
Filewatcher 1.0.0 is released! There are no more differences with the `README` from the git-repository.

**Comment by thomasfl** [comment] 2017-09-25 07:39
Super Alex! If I ever go to Moscow, or you ever happen to be in Oslo, then I'll buy you a drink.

https://media.giphy.com/media/LSNqpYqGRqwrS/giphy.gif

**Comment by AlexWayfer** [comment] 2017-09-25 08:30
Thank you, Thomas, this is very tempting and kind offer :hugs:
